name: Publish artifact
on:
  workflow_call:
    inputs:
      release_name:
        description: "Release name"
        required: false
        type: string
        default: "Latest files"
      release_tag:
        description: "Release tag"
        required: false
        type: string
        default: "latest"

jobs:
  publish:
    name: Publish artifact
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Download artifact
      uses: actions/download-artifact@main

    - name: Publish ${{ inputs.release_tag }} release
      uses: softprops/action-gh-release@master
      with:
        name: ${{ inputs.release_name }}
        tag_name: ${{ inputs.release_tag }}
        draft: false
        prerelease: false
        files: "**/*.*"