name: Userspace Build
on: [push, workflow_dispatch]

jobs:
  build:
    name: Userspace build
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        keyboard: [lily58]
        conv: [elite_pi]
        split: ['']
        pet: ['', LUNA, FELIX]
        branch: ['']
        include:
        - keyboard: crkbd
          conv: elite_pi
          split: ''
        - keyboard: lily58
          conv: elite_pi
          split: ''
          repo: splitkb/qmk_firmware
          branch: elora

    steps:
    - name: Configure safe directory
      run : git config --global --add safe.directory '*'

    - name: Checkout QMK
      if: ${{ !matrix.repo }}
      uses: actions/checkout@v4.0.0
      with:
        repository: qmk/qmk_firmware
        ref: ${{ matrix.branch }}
        submodules: true

    - name: Checkout QMK
      if: ${{ matrix.repo }}
      uses: actions/checkout@v4.0.0
      with:
        repository: ${{ matrix.repo }}
        ref: ${{ matrix.branch }}
        submodules: true

    - name: Checkout userspace
      uses: actions/checkout@v4.0.0
      with:
        path: users/${{ github.actor }}
        persist-credentials: false

    - name: Compile
      env:
        split: ${{ matrix.split }}
      working-directory: users/${{ github.actor }}/keymaps/
      run: >
        qmk compile -j $(nproc) ${{ matrix.keyboard }}.json
        -e CONVERT_TO=${{ matrix.conv }} -e SPLIT=${{ matrix.split }} -e TARGET=${{ matrix.keyboard }}${split:+_$split}

    - name: Archive firmware
      uses: actions/upload-artifact@main
      with:
        retention-days: 3
        name: ${{ matrix.keyboard }}_${{ matrix.split }}
        path: |
          *.hex
          *.bin
          *.uf2
