name: Userspace Build
on:
  push:
    paths-ignore:
      - "**.md"
      - "**.py"
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        keyboard: [crkbd, lily58]
        split: [""]

    steps:
      - name: Checkout QMK
        uses: actions/checkout@main
        with:
          repository: qmk/qmk_firmware
          ref: develop
          submodules: true

      - name: Checkout userspace
        uses: actions/checkout@main
        with:
          path: users/${{ github.actor }}
          persist-credentials: false

      - name: Setup safe directory
        run: git config --global --add safe.directory '*'

      - name: Compile
        working-directory: users/${{ github.actor }}/keymaps/
        run: qmk compile -j $(nproc) ${{ matrix.keyboard }}.json -e SPLIT=${{ matrix.split }}

      - name: Archive firmware
        uses: actions/upload-artifact@main
        with:
          retention-days: 1
          name: ${{ matrix.keyboard }}_${{ matrix.split }}
          path: |
            *.hex
            *.bin
            *.uf2

  release:
    needs: build
    uses: ./.github/workflows/publish-artifact.yaml
    with:
      release_name: Firmware
      release_tag: latest

  purge:
    uses: ./.github/workflows/purge-workflow.yaml
    with:
      purge-age: 5
      delete-all-completed: false
      delete-all-incomplete: false

