name: Userspace Build
on: [push, workflow_dispatch]

jobs:
  build:
    name: Userspace build
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        keyboard: [lily58]
        conv: [elite_pi]
        split: ['']
        pet: ['', LUNA, FELIX]
        include:
        - keyboard: crkbd
          conv: elite_pi
          split: ''

    steps:
    - name: Configure safe directory
      run : git config --global --add safe.directory '*'

    - name: Checkout QMK
      if: ${{ matrix.conv == '' }}
      uses: actions/checkout@v4.0.0
      with:
        repository: qmk/qmk_firmware
        ref: ${{ matrix.branch }}
        submodules: true

    - name: Checkout QMK
      if: ${{ matrix.conv != '' }}
      uses: actions/checkout@v4.0.0
      with:
        repository: ${{ matrix.repo }}
        ref: ${{ matrix.branch }}
        submodules: true

    - name: Checkout userspace
      uses: actions/checkout@v4.0.0
      with:
        path: users/${{ github.actor }}
        persist-credentials: false

    - name: Build
      continue-on-error: false
      working-directory: users/${{ github.actor }}/keymaps
      env:
        build_args: -e CONVERT_TO=${{ matrix.conv }} -e SPLIT=${{ matrix.split }} -e OLED=${{ matrix.pet }}
      run: qmk -v compile -j 3 ${{ env.build_args }} ${{ matrix.keyboard }}.json

    - name: Setup variables
      env:
        conv_suffix: $([ ${{ matrix.conv }} ] && printf "_${{ matrix.conv }}")
        split_suffix: $([ ${{ matrix.split }} ] && printf "_${{ matrix.split }}")
        pet_suffix: $([ ${{ matrix.pet }} ] && printf "_${{ matrix.pet }}")
        repo_suffix: $([ ${{ matrix.repo }} ] && printf "_${{ matrix.repo }}")        
        branch_suffix: $([ ${{ matrix.branch }} ] && printf "_${{ matrix.branch }}")        
      run: |
        echo "file_suffix=${{ env.conv_suffix }}${{ env.split_suffix }}${{ env.pet_suffix }}" >> $GITHUB_ENV
        echo "archive_name=${{ matrix.keyboard }}${{ env.conv_suffix }}" >> $GITHUB_ENV

    - name: Rename uf2
      if: ${{ matrix.conv != '' }}
      continue-on-error: true
      run: for file in *.uf2; do mv -v $file ${file%.*}${{ env.file_suffix }}.uf2; done

    - name: Archive firmware
      uses: actions/upload-artifact@v3
      continue-on-error: true
      with:
        retention-days: 60
        name: ${{ env.archive_name }}
        path: |
          *.hex
          *.bin
          *.uf2
