name: Development Build
on:
  schedule:
  - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        keyboard: [lily58, crkbd]
        conv: [elite_pi]
        split: ['']
        branch: [develop]

    steps:
    - name: Add safe directory
      run : git config --global --add safe.directory '*'

    - name: Checkout ${{ matrix.branch }} branch
      uses: actions/checkout@v4.2.1
      with:
        repository: qmk/qmk_firmware
        ref: ${{ matrix.branch }}
        submodules: true

    - name: Checkout userspace
      uses: actions/checkout@v4.2.1
      with:
        path: users/${{ github.actor }}
        persist-credentials: false

    - name: Build
      continue-on-error: true
      working-directory: users/${{ github.actor }}/keymaps
      env:
        build_args: -e CONVERT_TO=${{ matrix.conv }} -e SPLIT=${{ matrix.split }}
      run: qmk -v compile -j 3 ${{ env.build_args }} ${{ matrix.keyboard }}.json

    - name: Setup variables
      env:
        conv_suffix: $([ -n "${{ matrix.conv }}" ] && printf "_${{ matrix.conv }}")
        split_suffix: $([ -n "${{ matrix.split }}" ] && printf "_${{ matrix.split }}")
      run: |
        echo "file_suffix=${{ env.conv_suffix }}${{ env.split_suffix }}" >> $GITHUB_ENV
        echo "archive_name=${{ matrix.keyboard }}${{ env.conv_suffix }}" >> $GITHUB_ENV
        
    - name: Rename firmware
      if: ${{ matrix.conv != '' }}
      continue-on-error: true
      run: for file in *.uf2; do mv -v $file ${file%.*}${{ env.file_suffix }}.uf2; done

    - name: Archive firmware
      uses: actions/upload-artifact@v4
      continue-on-error: true
      with:
        retention-days: 3
        name: ${{ env.archive_name }}
        path: |
          *.hex
          *.bin
          *.uf2